language: java
sudo: false
jdk: openjdk11

services:
  - docker

before_install:
  - cd 7wonders

install:
  # maven pour build notre application
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 

before_script:
  # - docker build serveur -t 7wonders:gameserver
  # - docker build client -t 7wonders:client
  - docker-compose --version
  - docker ps -a -q
  - docker-compose build
  - docker images


jobs:
  include:
  - stage: "Tests unitaires"
    name: "Moteur"
    script:
      - mvn test

  - stage: "Tests d'integration"
    name: "PlayerManagerImpl"
    script:
      - mvn failsafe:integration-test
      
  - stage: "Execution avec Docker"
    name: "Statistiques"
    script:
      - docker-compose up
      - docker rm $(docker ps -a -q)
      