language: java
jdk: openjdk11

services:
  - docker

before_install:
  - cd 7wonders

install:
  # maven pour build notre application
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  # - docker build serveur -t 7wonders:gameserver
  # - docker build client -t 7wonders:client
  - docker-compose --version
  - docker ps -a -q
  - docker-compose build
  - docker images

jobs:
  include:
  - stage: "Metrics"
    name: "Semgrep"
    script:
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci client/
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci gameserver/
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci statsserver/

  - stage: "Tests unitaires"
    name: "Moteur"
    script:
      - mvn test

  - stage: "Tests d'integration"
    name: "StatServer"
    script:
      - docker build statsserver -t 7wonders:statsserver
      - cd gameserver
      - docker run -d --name serverstat_test -p 1335:1335 7wonders:statsserver
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#sendStatsWorkTest
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#finishStatsTest
      #le serveur est stoper car le finish a mis fin (ce test et fait pour tester la non accessibilité du serveur)
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#sendStatsServerDownTest
      - docker start serverstat_test
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#realUseTest

  - stage: "Execution avec Docker 3 joueurs"
    name: "Statistiques 3j"
    script:
      - docker-compose up --scale client=3
      - docker rm $(docker ps -a -q)

  - stage: "Execution avec Docker 7 joueurs"
    name: "Statistiques 7j"
    script:
      - docker-compose up --scale client=7
      - docker rm $(docker ps -a -q)

  - stage: "Tests d'integration serveur de jeu"
    name: "serveur jeu"
    script:
      - docker build client -t 7wonders:client
      - cd gameserver
      - docker run -e PROFILE=IT -e PORT=12345 -e IP=localhost -p 12345:12345 -d --name client1 7wonders:client
      - docker run -e PROFILE=IT -e PORT=12346 -e IP=localhost -p 12346:12345 -d --name client2 7wonders:client
      - docker run -e PROFILE=IT -e PORT=12347 -e IP=localhost -p 12347:12345 -d --name client3 7wonders:client
      - docker run -e PROFILE=IT -e PORT=12348 -e IP=localhost -p 12348:12345 -d --name client4 7wonders:client
      - docker run -e PROFILE=IT -e PORT=12349 -e IP=localhost -p 12349:12345 -d --name client5 7wonders:client
      - mvn failsafe:integration-test -Dit.test=servergame.integration.RequestToPlayerIT#setNbPlayer