language: java
jdk: openjdk11

services:
  - docker

before_install:
  - chmod +x scripts/*.sh
  - export PATH=$(pwd)/scripts:$PATH
  - cd 7wonders

install:
  # maven pour build notre application
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
  - stage: "Metrics"
    name: "Semgrep"
    script:
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci client/
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci gameserver/
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci statsserver/

  - stage: "Tests unitaires"
    script:
      - mvn test

  - stage: "Tests d'integration Moteur-Statistiques"
    script:
      - integration_tests.sh statsserver

  - stage: "Tests d'integration Moteur-Client"
    script:
      - integration_tests.sh client

  - stage: "Test applicatif pour 3 joueurs"
    script:
      - before_script.sh
      - docker-compose up --scale client=3
      - docker rm $(docker ps -a -q)

  - stage: "Test applicatif pour 7 joueurs"
    script:
      - before_script.sh
      - docker-compose up --scale client=7
      - docker rm $(docker ps -a -q)
