language: java
jdk: openjdk11

services:
  - docker

before_install:
  - cd 7wonders

install:
  # maven pour build notre application
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  # - docker build serveur -t 7wonders:gameserver
  # - docker build client -t 7wonders:client
  - docker-compose --version
  - docker ps -a -q
  - docker-compose build
  - docker images

jobs:
  include:
  - stage: "Metrics"
    name: "Semgrep"
    script:
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep --help
      - echo "----------------- CLIENT -----------------"
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci client/
      - echo "----------------- MOTEUR -----------------"
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci gameserver/
      - echo "----------------- STATISTIQUES -----------------"
      - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci statsserver/
    
    name: "SonarQ"
    script:
      - echo "----------------- SONARQ -----------------"
      - docker run --rm -e SONAR_HOST_URL="http://localhost:9000" -e SONAR_LOGIN="7wonders" -v "${PWD}:/src" sonarsource/sonar-scanner-cli

  - stage: "Tests unitaires"
    name: "Moteur"
    script:
      - mvn test

  - stage: "Tests d'integration"
    name: "StatServer"
    script:
      - docker build statsserver -t 7wonders:statsserver
      - cd gameserver
      - docker run -d --name serverstat_test -p 1335:1335 7wonders:statsserver
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#sendStatsWorkTest
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#finishStatsTest
      #le serveur est stoper car le finish a mis fin (ce test et fait pour tester la non accessibilité du serveur)
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#sendStatsServerDownTest
      - docker start serverstat_test
      - mvn failsafe:integration-test -Dit.test=servergame.integration.StatsServerTestIT#realUseTest

  - stage: "Execution avec Docker"
    name: "Statistiques"
    script:
      - docker-compose up --scale client=5
      - docker rm $(docker ps -a -q)