language: java
jdk: openjdk11

services:
  - docker

before_install:
  - chmod +x scripts/*.sh
  - export PATH=$(pwd)/scripts:$PATH
  - cd 7wonders

install:
  # maven pour build notre application
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: "Metrics"
      name: "Semgrep"
      script:
        - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci client/
        - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci gameserver/
        - docker run --rm -v "${PWD}:/src" returntocorp/semgrep -l fr --config=p/r2c-ci statsserver/

    - stage: "Tests unitaires"
      script:
        - mvn test

    - stage: "Tests d'integration Moteur-Statistiques"
      script:
        - integration_tests.sh statsserver

    - stage: "Tests d'integration Moteur-Client"
      script:
        - integration_tests.sh gameserver

    - stage: "Test applicatif pour 3 joueurs"
      script:
        - before_script.sh
        - docker-compose up --scale client=3
        - docker rm $(docker ps -a -q)

    - stage: "Test applicatif pour 7 joueurs"
      script:
        - before_script.sh
        - docker-compose up --scale client=7
        - docker rm $(docker ps -a -q)

    - stage: "Tests d'integration joueur"
      name: "IT joueur"
      script:
        - docker network create --subnet=172.22.0.0/16 itNetwork
        - docker build client -t 7wonders:client
        - docker build gameserver -t 7wonders:gameserver
        - cd client
        #on a pas de serveur lancer -> echec
        - mvn failsafe:integration-test -DgameServer.uri=http://localhost:1336 -DIP=172.22.0.1 -Dit.test=client.integration.InscriptionIT#inscriptionEchecTimeout
        #on lance le serveur, il y a de la place -> success
        - docker run --network="itNetwork" --ip 172.22.0.250 -p 1336:1336 -d --name serverjeu 7wonders:gameserver
        - mvn failsafe:integration-test -DgameServer.uri=http://localhost:1336 -DIP=172.17.0.1 -Dit.test=client.integration.InscriptionIT#inscriptionSuccess
        #on verifie que le server envois bien la position et le nombre des joueurs au client
        - mvn failsafe:integration-test -DgameServer.uri=http://localhost:1336 -DIP=172.17.0.1 -Dit.test=client.integration.InscriptionIT#initPositionOk
        - docker restart serverjeu
        - sleep 3s
        - docker run --network="itNetwork" -e GAME_IP=172.22.0.250 -d --name client1 7wonders:client
        - docker run --network="itNetwork" -e GAME_IP=172.22.0.250 -d --name client2 7wonders:client
        - mvn failsafe:integration-test -DgameServer.uri=http://localhost:1336 -DIP=172.17.0.1 -Dit.test=client.integration.InscriptionIT#initNbPlayerOK
        - docker stop serverjeu
        - sleep 10s
        - docker start serverjeu
        - docker start client1 client2
        - docker run --network="itNetwork" -e GAME_IP=172.22.0.250 -d --name client3 7wonders:client
        - docker run --network="itNetwork" -e GAME_IP=172.22.0.250 -d --name client4 7wonders:client
        - docker run --network="itNetwork" -e GAME_IP=172.22.0.250 -d --name client5 7wonders:client
        - docker run --network="itNetwork" -e GAME_IP=172.22.0.250 -d --name client6 7wonders:client
        - docker run --network="itNetwork" -e GAME_IP=172.22.0.250 -d --name client7 7wonders:client
        - mvn failsafe:integration-test -DgameServer.uri=http://localhost:1336 -DIP=172.17.0.1 -Dit.test=client.integration.InscriptionIT#inscriptionToManyPlayerOrClose

    - stage: "Tests d'integration jouer partie"
      name: "IT joueur partie"
      script:
        - docker build client -t 7wonders:client
        - docker build gameserver -t 7wonders:gameserver
        - cd client
        - docker run -p 1336:1336 -d --name serverjeu 7wonders:gameserver
        - sleep 10s #on attend que le serveur de jeu soit up
        - docker run -e GAME_IP=172.17.0.2 -d --name client1 7wonders:client
        - docker run -e GAME_IP=172.17.0.2 -d --name client2 7wonders:client
        - mvn failsafe:integration-test -DgameServer.uri=http://localhost:1336 -DIP=172.17.0.1 -Dit.test=client.integration.PlayGameIT#canCheckAllPlayerBoard
