version: '3'

services:
  game:
    image: 7wonders:gameserver
    build: ./gameserver
    environment:
      - STATS_IP=172.28.0.253
      - STATS_PORT=1335
    depends_on:
      - stats
    networks:
      testing_net:

  stats:
    image: 7wonders:statsserver
    build: ./statsserver
    networks:
      testing_net:
        ipv4_address: 172.28.0.253

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16